### ISSUE TITLE
Server install user friendlyness for the not so tech savvy

### ISSUE THREAD

**Issue by eddriesen** [theolizard/remote-numpad-server#1]
Hi, I had to punch a hole in windows firewall manually. While for me it's an easy task, I guess a lot of people don't know how to do that.

Also A full link to the server installer of the server on play store and your github readme would help the not so tech savvy. (I installed from f-droid, but came across a "does not work" on play"

Cheers! Great app, exactly what it needs to do without fuss!

**Comment by guillaumevpayet** [comment]
Hello, thank you for the feedback.
I will add more links and references to the video and the server download everywhere I can ;)
Kind regards

**Comment by guillaumevpayet** [comment]
I am trying to sunset the server program in favour of the HID connection (the default, now named "Bluetooth", in the Android app). Please try to use the HID connection and open new issues on the main remote-numpad GitHub page.
