### ISSUE TITLE
Feature: more verbose login than "echec de la connexion" 

### ISSUE THREAD

**Issue by hubyhuby** [theolizard/remote-numpad-server#4]
When connextion doesn t work in french is says "echec de la connexion" .
It would be nice to know what is the error.
I am in HID mode, I don t know why it don t work now (it used to work).
The error seems to come back much faster when the blutooth connexion with thcomputer actually works. 
I think My error should be " Connexion HID not accepted by the host "

**Comment by guillaumevpayet** [comment]
I am trying to sunset the server program in favour of the HID connection (the default, now named "Bluetooth", in the Android app). Please try to use the HID connection and open new issues on the main remote-numpad GitHub page.
