### ISSUE TITLE
"Failed to launch JVM" Error Message

### ISSUE THREAD

**Issue by JustinRamroop** [theolizard/remote-numpad-server#5]
This application was working before but now it just throws that error every time I try to launch. Java Version 8 Update 351 (from About Java GUI), latest version of Remote Numpad Server. 

Java console:
java version "19.0.1" 2022-10-18
Java(TM) SE Runtime Environment (build 19.0.1+10-21)
Java HotSpot(TM) 64-Bit Server VM (build 19.0.1+10-21, mixed mode, sharing)

I had previously installed Java 19.0.1 attempting to build an Android apk from another project, but was using Remote Numpad just fine after I had done that

**Comment by guillaumevpayet** [comment]
Thanks for the feedback. I will look into it.

**Comment by guillaumevpayet** [comment]
I am trying to sunset the server program in favour of the HID connection (the default, now named "Bluetooth", in the Android app). Please try to use the HID connection and open new issues on the main remote-numpad GitHub page.
